[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool]
hatch.metadata.allow-direct-references = true

[project]
name = "treeGenerator"
version = "0.0.1"
requires-python = ">=3.7"
dependencies = ["printBuddies @ git+https://github.com/matt-manes/printBuddies"]